# Generated by Django 4.2.5 on 2023-10-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('acc_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
